<!-- All "echo" are commented, otherwise the website won't be visualized as it should be.
     To see what's wrong of a SQL comment, "echo" should be uncommented.
     In order to use "POST" method within HTML, it is essentiel to use "submit" button.
     Otherwise, the information between HTML and PHP will not be transferred.

     A concept map is defined by a JSON file containing nodes and links.

     A conceptMap database is used in order to store all information related to concept maps.
     This database contains 4 tables: Student, Class, Exam, TableJointure.

     1) In Student table, only the StudentID is stored but the SQL code is editable. It is therefore possible to store new
     information of a student such as the name, surname, date of birth etc.

     2) In Class table, only the ClassID is stored but the SQL code is editable. It is therefore possible to store new
     information of a class such as the name etc.

     3) In Exam table, only the ExamID is stored but the SQL code is editable. It is therefore possible to store new
     information of an exam such as the name etc.

     4) In TableJointure table, all information related to a concept map are stored. A concept map is generated by one student
    (the current user in our case) for a particular exam of a particular class. In addition, only one concept map can be returned
    for one exam of one class. Therefore class, exam and JSON information are defined as UNIQUE. In a possible scenario, if the
    student uploads a concept map for the first time, the INSERT request is used. If, on the other hand, the student has already
    uploaded a concept map but would like to upload a new one for the same exam of the same class, then the UPLOAD request is 
    used in order to update the old JSON by the new ONE.

    For import and export methods (in order to upload a JSON file into the database or to visualize a concept map selected
    from the database), it is essential to use DISTINCT request to prevent the duplicates. Because there may be several exams
    belonging to the same class.
-->

<!DOCTYPE html>
<html>

<head>
    <title>ConceptMappingToul</title>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="Style_etud.css" />
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;0,800;1,300;1,400;1,600;1,700;1,800&display=swap" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://unpkg.com/konva@7.0.3/konva.min.js"></script>
    <script src="https://kit.fontawesome.com/5cfb8f8806.js" crossorigin="anonymous"></script>
    <script src="script_etud.js" type="text/javascript"></script>
    <script src="canvas.js" type="text/javascript"></script>
</head>

<body>
    <?php
        // Turn of all error reporting
        error_reporting(0);

        // Session is started in order to store User ID information.
        // This will be used to access informations of current user from database.
        session_start();
        
        // Mariadb connection is established on local using 3306/7 as port, 'pi' as user and 'lmao' as password.
        $conn = mysqli_connect('localhost:3306', 'pi', 'lmao', ''); // Raspberry Pi
        //$conn = mysqli_connect('localhost:3307', 'root', '', ''); /// Local PC

        // If the connection doesn't work, it is probably the localhost or the PhpMyAdmin wasn't set well.
        // Make sure that right servername and port number, user ID and password was set.
        if(!$conn){
            die("Connection failed: <br>". mysqli_connect_error());
        }
        
        // Database conceptMaps is created to store all information related to concept maps of students.
        $sql = "CREATE DATABASE IF NOT EXISTS ConceptMaps";
        if ($conn->query($sql) === TRUE) {
        //  echo "Database created successfully <br>";
        } else {
        //  echo "Error creating database: <br>" . $conn->error;
        }
        
        // The database to work on is selected.
        // Line 41 and 51 should be modified to use another database.
        $conn -> select_db("ConceptMaps");
        
        // If the Student ID was't set yet, then transfer the information from index.html inside data variable.
        if(empty($_SESSION['loggedIn']) ) {
            $_SESSION['loggedIn'] = $_POST['data'];
       }
        
        // Student ID is set.
        $StudentID = $_SESSION['loggedIn'];  

        // A table is created in order to store student information. The only information stored is the ID. 
        // In order to store other information of student such as name, surname; add into this table.
        $sql = "CREATE TABLE IF NOT EXISTS Student (StudentID VARCHAR(255) NOT NULL UNIQUE) CHARSET = utf8";
        if ($conn->query($sql) === TRUE) {
        //  echo "Table created successfully <br>";
        } else {
        //  echo "Error creating table: <br>" . $conn->error;
        }
        
        // A table is created in order to store class information. The only information stored is the ID. 
        $sql = "CREATE TABLE IF NOT EXISTS Class (ClassID VARCHAR(255) NOT NULL UNIQUE) CHARSET = utf8";
        if ($conn->query($sql) === TRUE) {
        //  echo "Table created successfully <br>";
        } else {
        //  echo "Error creating table: <br>" . $conn->error;
        }
        
        // A table is created in order to store exam information. The only information stored is the ID. 
        $sql = "CREATE TABLE IF NOT EXISTS Exam (ExamID VARCHAR(255) NOT NULL UNIQUE) CHARSET = utf8";
        if ($conn->query($sql) === TRUE) {
        //  echo "Table created successfully <br>";
        } else {
        //  echo "Error creating table: <br>" . $conn->error;
        }
        
        // A table is created in order to store concept map information.
        // StudentID, ClassID, ExamID, JSON and Note related to a concept map are stored in this table.
        $sql = "CREATE TABLE IF NOT EXISTS TableJointure (`StudentID` VARCHAR(255) NOT NULL, `ClassID` VARCHAR(255) NOT NULL, `ExamID` VARCHAR(255) NOT NULL, `JSON` TEXT(4294967295), `Note` VARCHAR(255), CONSTRAINT `uniqueAttributes` UNIQUE (StudentID, `ClassID`, `ExamID`)) CHARSET =  utf8";
        if ($conn->query($sql) === TRUE) {
        //  echo "Table created successfully <br>";
        } else {
        // echo "Error creating table: <br>" . $conn->error;
        }
        
        // StudentID is inserted into the table.
        $sql = "INSERT INTO Student (StudentID) VALUES ('$StudentID')";
        if ($conn->query($sql) === TRUE) {
        //  echo "Informations inserted successfully <br>";
        } else {
        //  echo "Error inserting informations: <br>" . $conn->error;
        }
    ?>
    
    <!-- Menu flottant pour le canvas -->
    <div id="floating-toolbar" class="floating-toolbar" style="display: none;">
        <span title="Supprimer ce concept"
           class="floating-toolbar__button floating-toolbar__button--delete fas fa-times">
        </span>
    </div>

    <!-- Nav Header -->
    <ul>
        <li><a class="t1 active" href="#Aide" onclick="openNav()">Aide</a></li>
        <li><a class="t1" href="#Nouveau" onclick="New()">Nouveau</a></li>
        <li><a class="t1" href="#Exporter" onclick = "openForm3()">Exporter</a></li>
        <li><a class="t1" href="#Importer" onclick="openForm2()">Importer</a>
            <!--
            <ul style="display: none;">
                <li><input class="t1" type="file" onchange="importEtud(this)" accept=".json" multiple></li>
            </ul>
            -->
        </li>
        <li><a class="t1" href="#Télécharger" onclick="exportEtud()">Télécharger</a></li>
        
        <li style="float:right"><b class="t4 fas fa-sign-out-alt" onclick="openForm()"></b></li>
        <li style="float:right"><b class="t2 fas fa-redo" href="#redo_black"></b></li>
        <li style="float:right"><b class="t2 fas fa-undo" href="#undo_black"></b></li>
    </ul>

    <div id="myNav" class="overlay">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <div class="overlay-content">
          <a class="t1">En cours de construction</a>
        </div>
    </div>

    <!-- Tabs -->
    <div class="tab" id="theTab">
        <button class="t5 tablinks" onclick="openTab(event,'1')" id="t1">Projet 1
            <close id="c1" onClick="reply_click(this.id)">&times;</close>
        </button>
    </div>

    <div class="content"></div>
        <div id="P1" class="tabcontent">
            <div class="row">
                <!-- Canvas -->
                <div class="column1">
                    <div id="canvas-container1" class="canvas-container">
                        <canvas id="canvas"></canvas>
                    </div>
                    <div class="icon-bar">
                        <a href="#"><i class="fas fa-mouse-pointer"><span>Manipuler le graphe</span></i></a> 
                        <a href="#"><i class="far fa-square"><span>Créer un concept</span></i></a> 
                        <a href="#"><i class="fas fa-external-link-alt"><span>Créer un lien</span></i></a> 
                        <a href="#"><i class="fas fa-compress-arrows-alt"><span>Recentre la carte</span></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="form-popup centrer" id="myForm">
        <form class="form-container">
            <label for="psw"><a class="t9">Voulez-vous vous déconnecter ?</a></label>
        
            <button type="button" class="btn" onclick="validate()">Oui</button>
            <button type="button" class="btn cancel" onclick="closeForm()">Non</button>
        </form>
    </div>

    <!-- This form allows the student to 
            1) Import a concept map to the website by choosing it from the database.
            2) Import a concept map to the website by choosing it from the local PC.
    -->
    <!-- 1) Choose the class and exam information in order to select the concept map from DATABASE matching the class and exam name selected. -->
    <div class="form-popup2" id = "myForm2">
        <!-- Post method is used in order to transfer JS data to PHP using getInfoImport() method. -->
        <form class="form-container2" onsubmit = "return getInfoImport()"  method = "post" name = "myForm2" id = "myForm2">
            <ul style="padding-top: 5px; padding-bottom: 5px;">
                <li style="float:right" class="t10">Importer depuis la BDD
                    <!-- A concept map is defined by "class" and "exam" name which are provided by the student. -->
                    <select id = "classe2" name = "classe2">
                    <option value = "">Class</option>
                        <?php
                            // All class options of the current student from Class table are presented to the student as a drop down menu.
                            // SQL request SELECT is used as DISTINCT to prevent the duplicates.
                            $resultSet = $conn -> query("SELECT DISTINCT classID FROM tableJointure WHERE studentID = '" . $StudentID . "'");
                            $numResult = mysqli_num_rows($resultSet);
                            for ($i = 0; $i < $numResult; $i++) {
                                $row = mysqli_fetch_array($resultSet); 
                        ?>
                        <option value = "<?php echo $row["classID"] ?> "> <?php echo $row["classID"]?></option>
                        <?php
                            }
                        ?>
                </select>
                <!-- A concept map is defined by "class" and "exam" name which are provided by the student. -->
                <select id = "examen2" name = "examen2">
                    <option value = "">Examen</option>
                        <?php
                            // All exam options of the current student from Exam table are presented to the student as a drop down menu.
                            // SQL request SELECT is used as DISTINCT to prevent the duplicates.
                            $resultSet = $conn -> query("SELECT DISTINCT examID FROM tableJointure WHERE studentID = '" . $StudentID . "'");
                            $numResult = mysqli_num_rows($resultSet);
                            for ($i = 0; $i < $numResult; $i++) {
                                $row = mysqli_fetch_array($resultSet); 
                        ?>
                        <option value = "<?php echo $row["examID"] ?> "> <?php echo $row["examID"]?></option>
                        <?php
                            }
                        ?>
                </select>          
                <!-- A submit button is used to bring the concept map from database. -->  
                <input type="submit" id = "ExporterBDD" name="ExporterBDD" value="OK"/>
                </li>
                <!-- 2) Choose the file from local PC. -->
                <li style="float:right" class="t10">Importer depuis l'ordinateur<input class="button button1" type="file" onchange="importEtud(this)" accept=".json" multiple></li>
            </ul>
        </form>
    </div>

    <!-- This form allows the student to insert the concept map created into the database. -->
    <div class="form-popup2" id = "myForm3">
        <!-- Post method is used in order to transfer JS data to PHP using exportBDD() method. -->
        <form class="form-container2" onsubmit = "return exportBDD()" method = "post" name = "myForm" id = "myForm">
            <ul style="padding-top: 5px; padding-bottom: 5px;">
                <!-- A concept map is defined by "class" and "exam" name which are provided by the student. -->
                <li style="float:right" class="t10">Classe
                <select id = "classe" name = "classe">
                    <!-- A student can choose in which class to import the concept map. -->
                    <option value = "">Choisir</option>
                        <?php
                            // Existing class options are showed in a drop down menu.
                            // SQL request SELECT is used as DISTINCT to prevent the duplicates.
                            $resultSet = $conn -> query("SELECT DISTINCT classID FROM tableJointure WHERE studentID = '" . $StudentID . "'");
                            $numResult = mysqli_num_rows($resultSet);
                            for ($i = 0; $i < $numResult; $i++) {
                                $row = mysqli_fetch_array($resultSet); 
                        ?>
                        <option value = "<?php echo $row["classID"] ?> "> <?php echo $row["classID"]?></option>
                        <?php
                            }
                        ?>
                </select>
                <!-- A student can also import the concept map into a class which doesn't exist in the Class table. -->
                <input placeholder = "Ajouter un nouveau" id = "newClass" type="text" name="newClass" id = "newClass"/><hr/>               
                <!-- A student can choose in which exam to import the concept map. -->
                Examen <select id = "examen" name = "examen">
                    <option value = "">Choisir</option>
                        <?php
                            // Existing exam options are showed in a drop down menu.
                            // SQL request SELECT is used as DISTINCT to prevent the duplicates.
                            $resultSet = $conn -> query("SELECT DISTINCT examID FROM tableJointure WHERE studentID = '" . $StudentID . "'");
                            $numResult = mysqli_num_rows($resultSet);
                            for ($i = 0; $i < $numResult; $i++) {
                                $row = mysqli_fetch_array($resultSet); 
                        ?>
                        <option value = "<?php echo $row["examID"] ?> "> <?php echo $row["examID"]?></option>
                        <?php
                            }
                        ?>
                </select>
                <!-- A student can also import the concept map into a exam which doesn't exist in the Exam table. -->
                <input placeholder = "Ajouter un nouveau" id = "newExam" type="text" name="newExam"/><hr/>           
                <!-- A hidden value is used in order to transfer parameter between JS and PHP. -->  
                <input placeholder="" type = "hidden" id = "test1" name = "test1" value=""/>
                <!-- A submit button is used to import the concept map into the database. -->  
                <input type="submit" id = "ExporterBDD" name="ExporterBDD" value="OK"/>
                </li>
            </ul>
        </form>
    </div>

    <script>
        // This method is used to visualize a concept map from database.
        function getInfoImport(){
            // The student should choose which class the concept map belongs to.
            var classeMenu = document.getElementById("classe");
            var classeUser = classeMenu.options[classeMenu.selectedIndex].text;

            // The student should also choose which exam the concept map belongs to.
            var examenMenu = document.getElementById("examen");
            var examenUser = examenMenu.options[examenMenu.selectedIndex].text;
            
            // The selection made by student (class and exam) transferred to PHP in order to select concept map from database.
            var f = document.getElementById("myForm2");
            f.setAttribute('method',"post");
            f.setAttribute('action', 'Interface_etudiant.php')

            return true;
        }

        // This method is used to insert concept map into the current student's database.
        function exportBDD(){
            // Concept maps are represented by JSON including nodes and labels.
            // In order to insert the concept map into the database, Canvas is transformed to a JSON.
            $JSON = canvas_to_json();
            // A hidden input is used in order to pass variable from JS to PHP.
            // Variable transfers are essential to use the database through JS or vice-versa.
            document.getElementById("test1").value = canvas_to_json();

            // A student can 
                // 1) Choose a class from the drop down menu. 
            var classeMenu = document.getElementById("classe");
            var classeUser = classeMenu.options[classeMenu.selectedIndex].text;
                
                // 2) Insert a new class which is not yet inserted into the database.
                // If the drop down menu value is returned by "Choisir", that means the student chose the second option. 
            if(classeUser == "Choisir"){
                var classeMenu = document.getElementById("newClass");
                if(classeMenu.placeholder){
                    var classeUser = classeMenu.value;
                }
            }

            // A student can 
                // 1) Choose an exam from the drop down menu. 
            var examenMenu = document.getElementById("examen");
            var examenUser = examenMenu.options[examenMenu.selectedIndex].text;

            // 2) Insert a new exam which is not yet inserted into the database.
                // If the drop down menu value is returned by "Choisir", that means the student chose the second option. 
            if(examenUser == "Choisir"){
                var examenMenu = document.getElementById("newExam");
                if(examenMenu.placeholder){
                    var examenUser = examenMenu.value;
                }
            }

            // The selection made by student (class and exam) transferred to PHP in order to select concept map from database.
            var f = document.getElementById("myForm");
            f.setAttribute('method', "post");
            f.setAttribute('action', 'Interface_etudiant.php')

        return true;
        }
    </script>

    <?php            
        // This SQL request returns JSON from database.
        // This JSON matches the class and exam name chosen by the student.
        if(isset($_POST['classe2']) and isset($_POST['examen2'])){
                $classeImport = $_POST['classe2'];
                $examenImport = $_POST['examen2'];
                $sql = "SELECT JSON FROM TableJointure WHERE StudentID = '$StudentID' AND ClassID = '$classeImport' AND ExamID = '$examenImport'";
                $result = $conn->query($sql);
                if ($result->num_rows > 0) {
                    while($row = $result->fetch_assoc()) {
                        // TODO: In order to visualize the concept map on Canvas, should pass $row["JSON"] variable to New() JS method in script_etud.js
                        // TODO: Return an information to the student to imply the status of success of failure during export.
                        // $json = $row["JSON"];
                        // echo $json;             
                        // If echo is uncommented, the concept map brought in from the database will be visualized on PHP as text.
                    }
                } 
                // A concept map matching the class and exam information by the student couldn't be found.
                else {
                    // echo "0 results <br>";
                }
            }

        // These SQL requests insert the JSON to the database.
        // In order to insert the JSON to the database, the student should choose 
            // 1) which exam this concept map belongs to.
        if($_POST['examen'] == "" and isset($_POST['newExam'])){
            // A new exam information is inserted by the student.
            $newExam = $_POST['newExam'];
        }
        else{
            // Exam information is chosen from the drop down menu.
            $newExam = $_POST['examen'];
        }

            // 2) which class this concept map belongs to.
        if($_POST['classe'] == "" and isset($_POST['newClass'])){
            // A new class information is inserted by the student.
            $newClass = $_POST['newClass'];
        }
        else{
            // Class information is chosen from the drop down menu.
            $newClass = $_POST['classe'];
        }

        // Exam or class information are provided by the student.
        if($newExam && $newClass){
            // A new class is inserted into the Class table.
            $sql = "INSERT INTO Class (ClassID) VALUES ('$newClass')";
            if ($conn->query($sql) === TRUE) {
            //  echo "Informations inserted successfully <br>";
            } 
            else {
            //  echo "Error inserting informations: <br>" . $conn->error;
            }
            
            // A new exam is inserted into the Exam table.
            $sql = "INSERT INTO Exam (ExamID) VALUES ('$newExam')";
            if ($conn->query($sql) === TRUE) {
            //  echo "Informations inserted successfully <br>";
            } 
            else {
            //  echo "Error inserting informations: <br>" . $conn->error;
            }

            // The hidden value is transferred in order to import the JSON to the database.
            $JSON = $_POST['test1'];
            // The JSON value is modified because it is not possible to import the JSON directly into MariaDB.
            $JSON = mysqli_real_escape_string($conn, $JSON);
            // If the student has not yet imported a concept map to the current exam and the class,
            // then import the concept map created by the student to its own table;
            // Otherwise update the old JSON to become the new JSON.
            $sql = "IF NOT EXISTS (SELECT * FROM TableJointure WHERE StudentID = '$StudentID' AND ClassID = '$newClass' AND ExamID = '$newExam')
                    THEN INSERT INTO TableJointure (StudentID, ClassID, ExamID, JSON, Note) VALUES ('$StudentID', '$newClass', '$newExam', '$JSON', '');
                    ELSE UPDATE TableJointure SET TableJointure.JSON = '$JSON' WHERE StudentID = '$StudentID' AND ClassID = '$newClass' AND ExamID = '$newExam';
                    END IF";
            // TODO: Return an information to the student to imply the status of success of failure during import.
            if ($conn->query($sql) === TRUE) {
            //  echo "Informations inserted successfully <br>";
            } else {
            //    echo "Error inserting informations: <br>" . $conn->error;
            }
        }
    ?>

    <!-- Footer -->
    <footer class="t6">&copy; Copyright Université Paul Sabatier - Tout droit réservé - Version 13</footer>

    <script>
        document.getElementById("t1").click();
    </script>

</body>
</html>